In [13]:
import numpy as np
import pandas as pd
import nltk
from copy import deepcopy
# nltk.download('stopwords')
import requests
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from collections import Counter

In [14]:
def frequent_eleement(tokens):
    temp_dictionary={}
    for items in tokens:
        for i in range(len(items)-1):
            tempword=""
            tempword=tempword+items[i]
            tempword=tempword+items[i+1]
            if(tempword not in temp_dictionary):
                temp_dictionary[tempword]=1
            else:
                temp_dictionary[tempword]+=1                
    max=0
    ind=0
    for i in temp_dictionary:
        if temp_dictionary[i]>max:
            max=temp_dictionary[i]
            ind=i
    return ind

In [15]:
stringinitial = '''aman saman daman'''
string=""
for c in stringinitial:
    if c.isalpha() or c==" ":
        string+=c
tokens = word_tokenize(string)
stringInitial=[i+"<"for i in tokens]
stringsend=[]
for k in stringInitial:
    temp=[]
    for l in k:
        temp.append(l)
    stringsend.append(temp)
pd.DataFrame([stringsend])

                 0                   1                   2
0  [a, m, a, n, <]  [s, a, m, a, n, <]  [d, a, m, a, n, <]

In [16]:
def Byte_pair_encoding(string,answer_list,Pfreq):
    X=10
    temp_string=string
    for i in range(X):
        frequent_word=frequent_eleement(temp_string)
        Pfreq.append(frequent_word)
        strings=[]
        for j in temp_string:
            index_to_remove=[]
            leng=len(j)-1
            for i in range(leng):
                temp=""
                temp+=j[i]
                temp+=j[i+1]
                if(temp==frequent_word):
                   j[i]=frequent_word
                   index_to_remove.append(i+1)
                
            for k in index_to_remove:
                j.pop(k)
            strings.append(j)
        answer_list.append(deepcopy(strings))
        temp_string=strings
        
    return answer_list
answer_list=[]
Pfreq=[]
data=pd.DataFrame(Byte_pair_encoding(stringsend,answer_list,Pfreq))
# data.columns= [f"Word{i+1}" for i in range(len(stringsend))]
# data.insert(len(stringsend),"Freq. Char",Pfreq)
data

               0                 1                 2
0  [am, a, n, <]  [s, am, a, n, <]  [d, am, a, n, <]
1    [ama, n, <]    [s, ama, n, <]    [d, ama, n, <]
2      [aman, <]      [s, aman, <]      [d, aman, <]
3        [aman<]        [s, aman<]        [d, aman<]
4        [aman<]          [saman<]        [d, aman<]
5        [aman<]          [saman<]          [daman<]
6        [aman<]          [saman<]          [daman<]
7        [aman<]          [saman<]          [daman<]
8        [aman<]          [saman<]          [daman<]
9        [aman<]          [saman<]          [daman<]